# Generated by Django 4.2.4 on 2023-09-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumOperationCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('X', 'Pauli-X'), ('Y', 'Pauli-Y'), ('Z', 'Pauli-Z'), ('H', 'Hadamard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuantumStateCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('theta', models.FloatField()),
                ('phi', models.FloatField()),
            ],
        ),
    ]
